FLAGS=-0 
all: test.exe pcxtest.exe

test.exe: test.obj modex16.obj
	wcl $(FLAGS) test.obj modex16.obj
	
pcxtest.exe: pcxtest.obj modex16.obj
	wcl $(FLAGS) pcxtest.obj modex16.obj

test.obj: test.c modex16.h
	wcl $(FLAGS) -c test.c
	
pcxtest.obj: pcxtest.c modex16.h
	wcl $(FLAGS) -c pcxtest.c

modex16.obj: modex16.h modex16.c
	wcl $(FLAGS) -c modex16.c
