OBJS=main.obj lztimer.obj
INCLUDES=modex.inc keyb.inc palette.inc page.inc scroll.inc map.inc \
         constant.inc init.inc
PROGRAM=scroll

.c.obj:
   cl -c -Zi -Od -W4 $*.c

.asm.obj:
   masm -ml -zi $*.asm

.obj.exe:
   link /CO @$*.lnk

project:  scroll.exe gensq.exe genmap.exe genpal.exe

main.asm:  $(INCLUDES)

scroll.lnk:  makefile
   echo $(OBJS: =+)  > $*.lnk
   echo $(PROGRAM); >> $*.lnk

scroll.exe: $(OBJS) scroll.lnk
   link /CO @$*.lnk

gensq.obj: $*.c

gensq.lnk: makefile
   echo $*.obj; > $*.lnk

gensq.exe: $*.obj $*.lnk

genmap.obj: $*.c

genmap.lnk: makefile
   echo $*.obj; > $*.lnk

genmap.exe: $*.obj $*.lnk

genpal.obj: $*.c

genpal.lnk: makefile
   echo $*.obj; > $*.lnk

genpal.exe: $*.obj $*.lnk

