#!/bin/bash
wdis -a MXBB.OBJ > mxbb.asm
wdis -a MXCC.OBJ > mxcc.asm
wdis -a MXCG.OBJ > mxcg.asm
wdis -a MXCL.OBJ > mxcl.asm
wdis -a MXCR.OBJ > mxcr.asm
#wdis -a MXEL.OBJ > mxel.asm
wdis -a MXFB.OBJ > mxfb.asm
wdis -a MXFP.OBJ > mxfp.asm
wdis -a MXGC.OBJ > mxgc.asm
wdis -a MXGI.OBJ > mxgi.asm
wdis -a MXGM.OBJ > mxgm.asm
wdis -a MXGP.OBJ > mxgp.asm
wdis -a MXGV.OBJ > mxgv.asm
wdis -a MXHL.OBJ > mxhl.asm
wdis -a MXIT.OBJ > mxit.asm
wdis -a MXLL.OBJ > mxll.asm
wdis -a MXLN.OBJ > mxln.asm
wdis -a MXOT.OBJ > mxot.asm
wdis -a MXPB.OBJ > mxpb.asm
wdis -a MXPF.OBJ > mxpf.asm
wdis -a MXPG.OBJ > mxpg.asm
wdis -a MXPI.OBJ > mxpi.asm
wdis -a MXPN.OBJ > mxpn.asm
wdis -a MXPP.OBJ > mxpp.asm
wdis -a MXRA.OBJ > mxra.asm
wdis -a MXRP.OBJ > mxrp.asm
wdis -a MXSA.OBJ > mxsa.asm
wdis -a MXSC.OBJ > mxsc.asm
wdis -a MXSI.OBJ > mxsi.asm
wdis -a MXSL.OBJ > mxsl.asm
wdis -a MXSM.OBJ > mxsm.asm
wdis -a MXSP.OBJ > mxsp.asm
wdis -a MXSS.OBJ > mxss.asm
wdis -a MXTL.OBJ > mxtl.asm
wdis -a MXVS.OBJ > mxvs.asm
wdis -a MXWD.OBJ > mxwd.asm
wdis -a MXWM.OBJ > mxwm.asm
wdis -a MXWP.OBJ > mxwp.asm
wdis -a MXWR.OBJ > mxwr.asm
