CC = wcc386
CFLAGS = -s -Wall -Werror

OBJ = a_memory.obj conlib.obj console.obj  controls.obj engine.obj entity.obj font.obj image.obj  keyboard.obj message.obj  modeinit.obj render.obj  startup.obj  timer.obj verge.obj vc.obj  vdriver.obj vfile.obj fli.obj sound.obj mikmod.a

verge: $(OBJ)

