#define KEYS_H

/* KEY DEFINITIONS */
#define KEY_ENTER       13

/* SCAN CODE DEFINITIONS */
#define SCAN_A          30
#define SCAN_B          48
#define SCAN_C          46
#define SCAN_E          18
#define SCAN_F          33
#define SCAN_G          34
#define SCAN_K          37
#define SCAN_Q          16
#define SCAN_R          19
#define SCAN_S          31
#define SCAN_T          20
#define SCAN_W          17

#define SCAN_SPACE      57
#define SCAN_ENTER      28
#define SCAN_ESC        1

#define SCAN_LEFTSHIFT  42
#define SCAN_RIGHTSHIFT 54

#define SCAN_UP         72
#define SCAN_DOWN       80
#define SCAN_LEFT       75
#define SCAN_RIGHT      77

