#define VERSION_H

#define KEY_HELP                                               \
"T           Determine FPS\n"                                  \
"C           Cheat -- Fill screen with animations\n"           \
"R           Cheat, but save roads\n"                          \
"E           Toggle dirt/grass edging\n"                       \
"A           Toggle off/on animations\n"                       \
"SPACE       Randomize foreground and background\n"            \
"B           Randomize background\n"                           \
"ENTER       Randomize foreground\n"                           \
"G           Randomize amount of grassiness for next world\n"  \
"ESC         QUIT this damn program I'm sick of it!\n"         \
"S           Check out the SPRITE page\n"                      \
"K           Toggle Keyboard Delay ON/OFF\n"                   \
"F           Bring on the frog!\n"                             \
"W           Frog Watch mode\n"                                \
"ARROW KEYS  Move around in the world\n"

#define HEADER \
"ROADS version 15.0  -- Sloppyright (S) Eric W. Lund and Donald D. Dienst\n"

