;-----------------------------------------------------------------------
;
; XBMTOOLS - Include file
;
; XBMTOOLS.ASM export functions
;
;
;
; ****** XLIB - Mode X graphics library                ****************
; ******                                               ****************
; ****** Written By Themie Gouthas                     ****************
;
; egg@dstos3.dsto.gov.au
; teg@bart.dsto.gov.au
;-----------------------------------------------------------------------


	 global _x_pbm_to_bm            :proc
	 global _x_bm_to_pbm            :proc
