;-----------------------------------------------------------------------
;
; XCBITMAP - Include file
; This module was written by Matthew MacKenzie
; matm@eng.umd.edu
;
; XCBITMAP.ASM export functions
;
; ****** XLIB - Mode X graphics library                ****************
; ******                                               ****************
; ****** Written By Themie Gouthas                     ****************
;
; egg@dstos3.dsto.gov.au
; teg@bart.dsto.gov.au
;-----------------------------------------------------------------------

global _x_compile_bitmap         : proc
global _x_sizeof_cbitmap         : proc
global _x_put_cbitmap            : proc

