;-----------------------------------------------------------------------
;
; XCIRCLE - Include file
;
;   This module was written by Matthew MacKenzie
;   matm@eng.umd.edu
;
; XCIRCLE.ASM export functions
;
; ****** XLIB - Mode X graphics library                ****************
; ******                                               ****************
; ****** Written By Themie Gouthas                     ****************
;
; egg@dstos3.dsto.gov.au
; teg@bart.dsto.gov.au
;-----------------------------------------------------------------------

	global _x_circle         : proc
	global _x_filled_circle  : proc

