;-----------------------------------------------------------------------
;
; XPBITMAP - Include file
;
; XPBITMAP.ASM export functions
;
;
;
; ****** XLIB - Mode X graphics library                ****************
; ******                                               ****************
; ****** Written By Themie Gouthas                     ****************
;
; egg@dstos3.dsto.gov.au
; teg@bart.dsto.gov.au
;-----------------------------------------------------------------------


	 global _x_put_masked_pbm        :proc
         global _x_flip_masked_pbm       :proc
	 global _x_put_pbm               :proc
         global _x_flip_pbm              :proc
	 global _x_get_pbm               :proc
