;-----------------------------------------------------------------------
;
; XPBMCLIP - Include file
;
; XPBMCLIP.ASM export functions
;
;
;
; ****** XLIB - Mode X graphics library                ****************
; ******                                               ****************
; ****** Written By Themie Gouthas                     ****************
;
; egg@dstos3.dsto.gov.au
; teg@bart.dsto.gov.au
;-----------------------------------------------------------------------


	 global _x_put_masked_pbm_clipx  :proc
	 global _x_put_masked_pbm_clipy  :proc
	 global _x_put_masked_pbm_clipxy :proc

	 global _x_put_pbm_clipx         :proc
	 global _x_put_pbm_clipy         :proc
	 global _x_put_pbm_clipxy        :proc

