;-----------------------------------------------------------------------
;
; XPOINT - Include file
;
; XPOINT.ASM export functions
;
;
;
; ****** XLIB - Mode X graphics library                ****************
; ******                                               ****************
; ****** Written By Themie Gouthas                     ****************
;
; egg@dstos3.dsto.gov.au
; teg@bart.dsto.gov.au
;-----------------------------------------------------------------------


	 global _x_put_pix              :proc
	 global _x_get_pix              :proc
