;-----------------------------------------------------------------------
;
; XPOLYGON - Include file
;
; XPOLYGON.ASM export functions
;
;
;
; ****** XLIB - Mode X graphics library                ****************
; ******                                               ****************
; ****** Written By Themie Gouthas                     ****************
;
; egg@dstos3.dsto.gov.au
; teg@bart.dsto.gov.au
;-----------------------------------------------------------------------


	 global _x_triangle             :proc
         global _x_polygon              :proc
