;-----------------------------------------------------------------------
;
; XRECT - Include file
;
; XRECT.ASM export functions
;
;
;
; ****** XLIB - Mode X graphics library                ****************
; ******                                               ****************
; ****** Written By Themie Gouthas                     ****************
;
; egg@dstos3.dsto.gov.au
; teg@bart.dsto.gov.au
;-----------------------------------------------------------------------

	 global _x_rect_fill             :proc
	 global _x_rect_fill_clipped     :proc
	 global _x_rect_pattern          :proc
	 global _x_rect_pattern_clipped  :proc
	 global _x_cp_vid_rect           :proc
	 global _x_shift_rect            :proc
