;-----------------------------------------------------------------------
;
; XVBITMAP - Include file
;
; XVBITMAP.ASM export functions
;
;
;
; ****** XLIB - Mode X graphics library                ****************
; ******                                               ****************
; ****** Written By Themie Gouthas                     ****************
;
; egg@dstos3.dsto.gov.au
; teg@bart.dsto.gov.au
;-----------------------------------------------------------------------

	 global _x_store_vbm_image       :proc
	 global _x_put_masked_vbm        :proc
	 global _x_put_masked_vbm_clipx  :proc
	 global _x_put_masked_vbm_clipy  :proc
         global _x_put_masked_vbm_clipxy :proc
