pkzip -a xlib06.zip MAKEFILE

pkzip -a xlib06.zip XBEZIER.ASM
pkzip -a xlib06.zip XBMTOOLS.ASM
pkzip -a xlib06.zip XCBITMAP.ASM
pkzip -a xlib06.zip XCOMPPBM.ASM
pkzip -a xlib06.zip XDETECT.ASM
pkzip -a xlib06.zip XFILEIO.ASM
pkzip -a xlib06.zip XLINE.ASM
pkzip -a xlib06.zip XMAIN.ASM
pkzip -a xlib06.zip XMOUSE.ASM
pkzip -a xlib06.zip XPAL.ASM
pkzip -a xlib06.zip XPBITMAP.ASM
pkzip -a xlib06.zip XPBMCLIP.ASM
pkzip -a xlib06.zip XPOINT.ASM
pkzip -a xlib06.zip XRECT.ASM
pkzip -a xlib06.zip XRLETOOL.ASM
pkzip -a xlib06.zip XTEXT.ASM
pkzip -a xlib06.zip XVBITMAP.ASM
pkzip -a xlib06.zip XCIRCLE.ASM
pkzip -a xlib06.zip XCLIPPBM.ASM
pkzip -a xlib06.zip XPOLYGON.ASM
pkzip -a xlib06.zip XFILL.ASM
pkzip -a xlib06.zip XVSYNC.ASM

pkzip -a xlib06.zip XCBITM32.C
pkzip -a xlib06.zip DEMO1.C
pkzip -a xlib06.zip DEMO2.C
pkzip -a xlib06.zip DEMO3.C
pkzip -a xlib06.zip DEMO4.C
pkzip -a xlib06.zip DEMO5.C
pkzip -a xlib06.zip DEMO6.C
pkzip -a xlib06.zip DEMO7.C
pkzip -a xlib06.zip DEMO8.C
pkzip -a xlib06.zip DEMO9.C
pkzip -a xlib06.zip DEMO10.CPP

pkzip -a xlib06.zip XMAKEVBM.C
pkzip -a xlib06.zip XPRINTF.C
pkzip -a xlib06.zip UPDATES.DOC
pkzip -a xlib06.zip XLIBREF1.DOC
pkzip -a xlib06.zip XLIBREF2.DOC
pkzip -a xlib06.zip DEMO7.EXE
pkzip -a xlib06.zip DEMO1.EXE
pkzip -a xlib06.zip DEMO2.EXE
pkzip -a xlib06.zip DEMO3.EXE
pkzip -a xlib06.zip DEMO4.EXE
pkzip -a xlib06.zip DEMO5.EXE
pkzip -a xlib06.zip DEMO6.EXE
pkzip -a xlib06.zip DEMO8.EXE
pkzip -a xlib06.zip DEMO9.EXE
pkzip -a xlib06.zip DEMO10.EXE

pkzip -a xlib06.zip FIXED6X8.FNT
pkzip -a xlib06.zip VAR6X8.FNT
pkzip -a xlib06.zip VARSWISL.FNT
pkzip -a xlib06.zip VARSWISB.FNT
pkzip -a xlib06.zip TIMPANI.FNT
pkzip -a xlib06.zip MODERNB.FNT
pkzip -a xlib06.zip CRISP6X9.FNT
pkzip -a xlib06.zip TINY4.FNT
pkzip -a xlib06.zip SMALTHIN.FNT

pkzip -a xlib06.zip XBEZIER.H
pkzip -a xlib06.zip XBMTOOLS.H
pkzip -a xlib06.zip XCBITMAP.H
pkzip -a xlib06.zip XCOMPPBM.H
pkzip -a xlib06.zip XDETECT.H
pkzip -a xlib06.zip XFILEIO.H
pkzip -a xlib06.zip XLIB.H
pkzip -a xlib06.zip XLIB_ALL.H
pkzip -a xlib06.zip XLINE.H
pkzip -a xlib06.zip XMOUSE.H
pkzip -a xlib06.zip XPAL.H
pkzip -a xlib06.zip XPBITMAP.H
pkzip -a xlib06.zip XPBMCLIP.H
pkzip -a xlib06.zip XPOINT.H
pkzip -a xlib06.zip XRECT.H
pkzip -a xlib06.zip XRLETOOL.H
pkzip -a xlib06.zip XTEXT.H
pkzip -a xlib06.zip XVBITMAP.H
pkzip -a xlib06.zip XCIRCLE.H
pkzip -a xlib06.zip XCLIPPBM.H
pkzip -a xlib06.zip XPOLYGON.H
pkzip -a xlib06.zip XFILL.H
pkzip -a xlib06.zip XVSYNC.H
pkzip -a xlib06.zip XCBITM32.H

pkzip -a xlib06.zip MODEL.INC
pkzip -a xlib06.zip XBEZIER.INC
pkzip -a xlib06.zip XBMTOOLS.INC
pkzip -a xlib06.zip XCBITMAP.INC
pkzip -a xlib06.zip XCOMPPBM.INC
pkzip -a xlib06.zip XDETECT.INC
pkzip -a xlib06.zip XFILEIO.INC
pkzip -a xlib06.zip XLIB.INC
pkzip -a xlib06.zip XLINE.INC
pkzip -a xlib06.zip XMAIN.INC
pkzip -a xlib06.zip XPAL.INC
pkzip -a xlib06.zip XPBITMAP.INC
pkzip -a xlib06.zip XPBMCLIP.INC
pkzip -a xlib06.zip XPOINT.INC
pkzip -a xlib06.zip XRECT.INC
pkzip -a xlib06.zip XRLETOOL.INC
pkzip -a xlib06.zip XTEXT.INC
pkzip -a xlib06.zip XVBITMAP.INC
pkzip -a xlib06.zip XVBMTOOL.INC
pkzip -a xlib06.zip XCIRCLE.INC
pkzip -a xlib06.zip XCLIPPBM.INC
pkzip -a xlib06.zip XPOLYGON.INC
pkzip -a xlib06.zip XFILL.INC
pkzip -a xlib06.zip XVSYNC.INC

pkzip -a xlib06.zip XLIB04S.LIB
pkzip -a xlib06.zip XLIB04C.LIB
pkzip -a xlib06.zip XLIB04L.LIB
pkzip -a xlib06.zip ZIP.BAT

